---
- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: restart elasticsearch
  service:
    name: elasticsearch
    state: restarted

- name: Set Elasticsearch server address
  command: zammad run rails r "Setting.set('es_url', '{{ elasticsearch_url | quote }}')"

- name: Build search index
  command: zammad run rake searchindex:rebuild

...
