---
- name: Converge
  hosts: all
  tasks:

    - name: Get private key content
      command: cat /etc/ssl/private/ssl-cert-snakeoil.key
      changed_when: false
      check_mode: false
      register: private_key

    - name: Get SSL certificate content
      command: cat /etc/ssl/certs/ssl-cert-snakeoil.pem
      changed_when: false
      check_mode: false
      register: certificate

    - name: Pass SSL key pair to zammad role
      set_fact:
        zammad_ssl_key:  "{{ private_key.stdout }}"
        zammad_ssl_cert:  "{{ certificate.stdout }}"

    - name: "Include ansible-role-zammad"
      include_role:
        name: "ansible-role-zammad"
