---
- name: Converge
  hosts: all
  vars:
    # Apply suggested Elasticsearch configuration
    es_config:
      http.max_content_length: 400mb
      indices.query.bool.max_clause_count: 2000

    # Install ingest-attachment plugin (this step requires JMESPath)
    es_plugins:
      - plugin: ingest-attachment
  tasks:

    - name: Get private key content
      command: cat /etc/ssl/private/ssl-cert-snakeoil.key
      changed_when: false
      check_mode: false
      register: private_key

    - name: Get SSL certificate content
      command: cat /etc/ssl/certs/ssl-cert-snakeoil.pem
      changed_when: false
      check_mode: false
      register: certificate

    - name: Pass SSL key pair to zammad role
      set_fact:
        zammad_ssl_key:  "{{ private_key.stdout }}"
        zammad_ssl_cert:  "{{ certificate.stdout }}"

    - name: "Include ansible-role-zammad"
      include_role:
        name: "ansible-role-zammad"
