---
- name: Prepare
  hosts: all
  vars:
    # Apply suggested Elasticsearch configuration
    es_config:
      http.max_content_length: 400mb
      indices.query.bool.max_clause_count: 2000

    # Install ingest-attachment plugin (this step requires JMESPath)
    es_plugins:
      - plugin: ingest-attachment
  tasks:

    - name: Install required packages
      apt:
        name:
          - sudo
          - gpg
          - ca-certificates
          - python3-cryptography
          - ssl-cert
        state: present
        update_cache: yes

    - name: "Include elastic.elasticsearch"
      include_role:
        name: "elastic.elasticsearch"

    - name: "Include geerlingguy.postgresql"
      include_role:
        name: "geerlingguy.postgresql"
