---
- name: Verify
  hosts: all
  tasks:
    - name: Check that Zammad web interface is available
      uri:
        url: https://localhost
        validate_certs: no
        return_content: yes
      register: this
      failed_when: "'Zammad Helpdesk' not in this.content"
